Website update graphics and mobile
CubeOfCheese/Ethicli pull request #338
Opened 2020-10-02 07:23 UTC by lindaicing

2020-10-02 07:26 UTC, lindaicing commented
New Homepage Content:
<img width="670" alt="Screen Shot 2020-10-02 at 12 25 14 AM" src="https://user-images.githubusercontent.com/38482675/94898068-c1772e80-0445-11eb-87dd-33186e4f5d66.png">
<img width="1139" alt="Screen Shot 2020-10-02 at 12 25 48 AM" src="https://user-images.githubusercontent.com/38482675/94898108-d358d180-0445-11eb-8444-a78dc91b591f.png">



Info page main:
<img width="410" alt="Screen Shot 2020-10-02 at 12 24 08 AM" src="https://user-images.githubusercontent.com/38482675/94897982-97be0780-0445-11eb-9184-4f0840bc3a1d.png">
<img width="411" alt="Screen Shot 2020-10-02 at 12 24 48 AM" src="https://user-images.githubusercontent.com/38482675/94898030-b02e2200-0445-11eb-9ffa-977fd3a6df2c.png">

2020-10-03 16:54 UTC, CubeOfCheese commented on Website-and-Backend/src/main/resources/templates/index.html
> +                        save you the time and energy it takes to be sure your purchase reflects your values.</p>
I feel like this sounds better the way it was before

2020-10-03 16:55 UTC, CubeOfCheese commented
Can you update the tagline?
"Ethicli helps you choose better products" ->
"Ethicli helps you shop for ethical products"

2020-10-03 16:56 UTC, CubeOfCheese commented
Good job with the updated info page for mobile! :)

2020-10-03 17:57 UTC, CubeOfCheese requested changes
Sorry I didn't notice this the first time around

2020-10-03 17:57 UTC, CubeOfCheese commented on Website-and-Backend/src/main/resources/templates/index.html
> +                    <p>Sometimes while shopping, we'll recomend more ethical products based on items that you are viewing.</p>
```suggestion
                    <p>Sometimes while shopping, we'll recommend more ethical products based on what you're shopping for.</p>
```
recommend has a typo
"items that you are viewing" doesn't sound natural

2020-10-03 18:20 UTC, CubeOfCheese approved these changes
:)

2020-10-03 18:20 UTC, merged