Added rating request buttons
CubeOfCheese/Ethicli pull request #344
Opened 2020-10-13 07:39 UTC by lindaicing

For both shops with and without badges
<img width="359" alt="Screen Shot 2020-10-13 at 12 37 45 AM" src="https://user-images.githubusercontent.com/38482675/95830303-51419600-0cec-11eb-98ef-e9d2545aebc1.png">
<img width="356" alt="Screen Shot 2020-10-13 at 12 37 56 AM" src="https://user-images.githubusercontent.com/38482675/95830321-57d00d80-0cec-11eb-9b53-fc79a2729e47.png">
<img width="363" alt="Screen Shot 2020-10-13 at 12 38 27 AM" src="https://user-images.githubusercontent.com/38482675/95830375-6a4a4700-0cec-11eb-8331-6a89cfe57391.png">

For shops with badges:
<img width="371" alt="Screen Shot 2020-10-13 at 12 38 52 AM" src="https://user-images.githubusercontent.com/38482675/95830406-7930f980-0cec-11eb-809e-17fd015d958a.png">
<img width="366" alt="Screen Shot 2020-10-13 at 12 39 03 AM" src="https://user-images.githubusercontent.com/38482675/95830419-80f09e00-0cec-11eb-9c70-57429260e4fd.png">
<img width="359" alt="Screen Shot 2020-10-13 at 12 39 19 AM" src="https://user-images.githubusercontent.com/38482675/95830437-89e16f80-0cec-11eb-9e99-f09f82434c86.png">

2020-10-13 07:47 UTC, lindaicing commented
Fixed styling:
<img width="364" alt="Screen Shot 2020-10-13 at 12 47 26 AM" src="https://user-images.githubusercontent.com/38482675/95831271-adf18080-0ced-11eb-8cb9-9247a5d7dc9a.png">
<img width="363" alt="Screen Shot 2020-10-13 at 12 47 42 AM" src="https://user-images.githubusercontent.com/38482675/95831297-b5188e80-0ced-11eb-8c2e-16084dd6556f.png">

2020-10-13 22:14 UTC, CubeOfCheese requested changes

2020-10-13 22:14 UTC, CubeOfCheese commented on Extension/popup-scripts/confetti.js
> +// open source MIT license from https://github.com/mathusummut/confetti.js
Hmmm does this belong in popup-scripts or style scripts? I'm not sure. I think I lean towards style scripts since it's entirely visual

2020-10-13 22:14 UTC, CubeOfCheese commented on Extension/popup-scripts/popup-norating.js
> +        document.getElementById("emailrequest").innerText = response;
The response will just be the exact thing that was sent in the request.
Isn't this where things are supposed to be getting hidden/exposed?

2020-10-13 22:14 UTC, CubeOfCheese commented on Extension/popup-scripts/popup-norating.js
> +uemail = "";
Why is there both uemail and useremailhtml?

2020-10-13 22:14 UTC, CubeOfCheese commented on Extension/popup-scripts/popup-norating.js
> +function windowOnload(){
Space after parentheses

2020-10-13 22:14 UTC, CubeOfCheese commented on Extension/popup-scripts/popup-norating.js
> +function windowOnload(){
Shouldn't ESLint have caught that?

2020-10-13 22:14 UTC, CubeOfCheese commented on Extension/popup-scripts/popup-norating.js
> +  document.getElementById("requestrating").addEventListener("click", () => {
Lines 9-17 should be in the .then clause. The click should just call the requestShop() function

2020-10-13 22:14 UTC, CubeOfCheese commented on Extension/popup-scripts/popup-norating.js
> +  document.getElementById("requestrating").addEventListener("click", () => {
As of right now it looks like that function isn't getting called which means nothing is getting sent to the backend

2020-10-13 22:21 UTC, lindaicing commented on Extension/popup-scripts/confetti.js
> +// open source MIT license from https://github.com/mathusummut/confetti.js
Stylescripts isn't a thing for the extensions, it's separated by stylesheets or popup-scripts. stylesheets are CSS only and confetti is all js

2020-10-13 22:24 UTC, lindaicing commented on Extension/popup-scripts/popup-norating.js
> +        document.getElementById("emailrequest").innerText = response;
Should the entire ".this" statement just be removed?

2020-10-13 22:27 UTC, lindaicing commented on Extension/popup-scripts/popup-norating.js
> +uemail = "";
uemail is to test for spaces using regex, and then conditionally display text if the user types in the email. userEmailHTML will depend on what the actual user input is

2020-10-13 22:34 UTC, lindaicing commented on Extension/popup-scripts/popup-norating.js
> +  document.getElementById("requestrating").addEventListener("click", () => {
> Lines 9-17 should be in the .then clause. The click should just call the requestShop() function

The ".then" doesn't work, attached neither to the event listener nor the requestShop() function. I added requestShop() before the rest of the code instead

2020-10-14 00:17 UTC, CubeOfCheese commented on Extension/popup-scripts/confetti.js
> +// open source MIT license from https://github.com/mathusummut/confetti.js
Okay sounds good. That's my bad.

2020-10-14 00:19 UTC, CubeOfCheese commented on Extension/popup-scripts/popup-norating.js
> +  document.getElementById("requestrating").addEventListener("click", () => {
The .then won't work until the backend is running this api. So it makes sense that it wasn't executing

2020-10-14 00:19 UTC, CubeOfCheese commented on Extension/popup-scripts/popup-norating.js
> +  document.getElementById("requestrating").addEventListener("click", () => {
"This api" meaning the /feedback api.

2020-10-14 00:24 UTC, CubeOfCheese commented on Extension/popup-scripts/popup-norating.js
> +        document.getElementById("emailrequest").innerText = response;
Nope. We should keep it and move the other stuff in here. Also, we can display an error message if the request failed using a catch block. It would look like this
fetch(whatever)
.then((response) => doStuff;)
.catch((error) => {
  // Here's where to put all the dom manipulatio to display an error message
  console.log('aw nards' + error.message); // not necessary
});

2020-10-14 05:35 UTC, lindaicing commented on Extension/popup-scripts/popup-norating.js
> +        document.getElementById("emailrequest").innerText = response;
We did it wahey

2020-10-14 06:32 UTC, lindaicing commented
![Uploading Screen Shot 2020-10-13 at 11.32.17 PM.png…]()

2020-10-14 06:56 UTC, CubeOfCheese submitted a review, later dismissed

2020-10-14 06:56 UTC, CubeOfCheese commented on Extension/popup-scripts/popup-norating.js
> +}
This concerns me a tiny bit. I think it would be better to retrieve the email in the requestShop function, but it´s okay for now.

2020-10-14 06:56 UTC, CubeOfCheese commented on Extension/popup-scripts/popup-norating.js
> +        });
Should we track this with Gooogle Analytics?

2020-10-15 02:38 UTC, lindaicing commented on Extension/popup-scripts/popup-norating.js
> +}
Moved it, works well

2020-10-15 02:40 UTC, lindaicing commented on Extension/popup-scripts/popup-norating.js
> +        });
<img width="307" alt="Screen Shot 2020-10-14 at 7 39 52 PM" src="https://user-images.githubusercontent.com/38482675/96070411-098a4e00-0e55-11eb-92e7-99ca2e7ac02f.png">

2020-10-15 02:43 UTC, lindaicing commented on Extension/popup-scripts/popup-norating.js
> +        });
<img width="452" alt="Screen Shot 2020-10-14 at 7 42 54 PM" src="https://user-images.githubusercontent.com/38482675/96070645-77367a00-0e55-11eb-93f6-45a96f96e370.png">
<img width="458" alt="Screen Shot 2020-10-14 at 7 43 11 PM" src="https://user-images.githubusercontent.com/38482675/96070664-7f8eb500-0e55-11eb-9d88-2cdfc449644d.png">

2020-10-15 06:15 UTC, CubeOfCheese requested changes
Im pretty sure useremail is just going to be an empty string with how the code is right now

2020-10-15 06:15 UTC, CubeOfCheese commented on Extension/popup-scripts/popup-norating.js
> +          console.log(response);
remove the print statement

2020-10-15 06:15 UTC, CubeOfCheese commented on Extension/popup-scripts/popup-norating.js
> +          console.log(response);
remove print

2020-10-15 06:15 UTC, CubeOfCheese commented on Extension/popup-scripts/popup-norating.js
> +          userEmailHTML = document.getElementById("emailrequest").value;
Wait I dont understand how this would work here. The .then clause runs after the request is sent so thatś too late to retrieve the email

2020-10-15 06:15 UTC, CubeOfCheese commented on Extension/popup-scripts/popup-norating.js
> +let userEmailHTML = "";
Shouldnt be a global variable since it is only used in the requestShop function

2020-10-15 06:45 UTC, CubeOfCheese approved these changes
Yay better UX!

2020-10-15 06:47 UTC, merged